parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: false

  ExtraConfig:
    horizon::cinder_options: { enable_backup: true }

  NovaEnableRbdBackend: false

  GlanceBackend: file

  # Config NFS for glance images.
  GlanceNfsEnabled: true
  GlanceNfsShare: '60.30.157.253:/root/data/nfs/glance-images'
  GlanceNfsOptions: 'rw,sync,context=system_u:object_r:svirt_sandbox_file_t:s0'  


  # Config NFS for Cinder Volumes.
  CinderEnableNfsBackend: true
  CinderNfsMountOptions: 'nfsvers=3,rw,sync,intr,bg'
  CinderNfsServers: '60.30.157.253:/root/data/nfs/cinder-volumes'

  # Config NFS for Cinder Backups
  CinderBackupBackend: nfs
  CinderBackupNfsMountOptions: 'nfsvers=3,rw,sync,intr,bg'
  CinderBackupNfsShare: '60.30.157.253:/root/data/nfs/cinder-backups'



