heat_template_version: rocky
parameters:
#------------------------------------------------------------------------------------#
  ControlPlaneIp:
    type: string
  ControlPlaneSubnetCidr:
    type: string
  ControlPlaneDefaultRoute:
    type: string
  ControlPlaneStaticRoutes:
    type: json
  ControlPlaneMtu:
    type: number
#------------------------------------------------------------------------------------#
  InternalApiIpSubnet:
    type: string
  InternalApiMtu:
    type: number
  InternalApiInterfaceRoutes:
    type: json

  AZ-0-OSC-CP0EC2MetadataIp:
    type: string

  DnsServers: # Override this via parameter_defaults
    type: comma_delimited_list
#------------------------------------------------------------------------------------#
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
#------------------------------------------------------------------------------------#
              - type: interface
                name: ens3
                use_dhcp: false
                dns_servers:
                  get_param: DnsServers
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop:
                    get_param: ControlPlaneDefaultRoute
#------------------------------------------------------------------------------------#
              - type: interface
                name: ens4
                use_dhcp: false
                addresses:
                - ip_netmask:
                    get_param: InternalApiIpSubnet
                routes:
                - default: true
                  next_hop: 60.30.155.1    
#------------------------------------------------------------------------------------#
              - type: ovs_bridge
                name: br-service0
                use_dhcp: false
                mtu: 1500
                members:
                  - type: interface
                    name: ens5
                    mtu: 1500
#------------------------------------------------------------------------------------#
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl

